version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:5432"
    env_file: 
      - ".env"

volumes:
  pgdata:
