# models/permission.rb
class Permission < Sequel::Model
  many_to_many :roles, join_table: :role_permissions
end

# Table: permissions
# Columns:
#  id          | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name        | text    | NOT NULL
#  description | text    |
# Indexes:
#  permissions_pkey     | PRIMARY KEY btree (id)
#  permissions_name_key | UNIQUE btree (name)
# Referenced By:
#  role_permissions | role_permissions_permission_id_fkey | (permission_id) REFERENCES permissions(id)
